### ISSUE TITLE
Linux documents path incorrect

### ISSUE THREAD

**Issue by jpcima** [surge-synthesizer/sst-plugininfra#32]
Hi, the function `bestDocumentsFolderPathFor` deduces its path incorrectly on Linux.

The problem is that sst-plugininfa considers `XDG_DOCUMENTS_DIR` as environment variable, which it isn't.

It's a variable which is picked up from the file `$XDG_CONFIG_HOME/user-dirs.dirs`.
The format of the file is a simplified shell-style syntax.
It may contain lines such as: `XDG_DOCUMENTS_DIR="$HOME/documents"`
Glib has a reference implementation of that parsing procedure.

If that would be fine, I can work on an implementation of this feature.

Reference:
- https://www.freedesktop.org/wiki/Software/xdg-user-dirs/
- https://github.com/GNOME/glib/blob/0e112b457d54a69b0c680af163687d0deba727c2/glib/gutils.c#L2144

**Comment by baconpaul** [comment]
Hi!

Yes @robbert-vdh told me the same and threatened an implementation also. I would love help in this regard and welcome a pr with a fix! Thank you!

**Comment by baconpaul** [comment]
I presume you could copy the glib version though not couple to gmone correct?

**Comment by jpcima** [comment]
> I presume you could copy the glib version though not couple to gnome correct?

In fact no, I would rather write a piece of code that I can reuse at will and free of dependencies, because it's not the first time I this need comes up in the scope of a plugin.

**Comment by baconpaul** [comment]
And thanks!

**Comment by robbert-vdh** [comment]
I know there's a specification for the file format somewhere, but I can never find it. There's not much to it, but I remember there being a couple good to know things in there like what can (or should) be quoted and what cannot, and that `$HOME` is the only environment variable that needs to be expanded.

**Comment by baconpaul** [comment]
Closed with #33
